// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu4Sdzdc6ZJxQ25KxD-qrOPPE1FnGqtZU',
    appId: '1:822102067110:web:3fadd5461d6145db077167',
    messagingSenderId: '822102067110',
    projectId: 'newpjorject',
    authDomain: 'newpjorject.firebaseapp.com',
    storageBucket: 'newpjorject.firebasestorage.app',
    measurementId: 'G-R8BT30J3FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAnJCvYMG7g3WpN8PSg8ANwKvu14J08S8',
    appId: '1:822102067110:android:34bcf195314fdf5a077167',
    messagingSenderId: '822102067110',
    projectId: 'newpjorject',
    storageBucket: 'newpjorject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm7Cv8P01IROollZ-on6lAnNi11vXczf0',
    appId: '1:822102067110:ios:af0ed85835d6555f077167',
    messagingSenderId: '822102067110',
    projectId: 'newpjorject',
    storageBucket: 'newpjorject.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm7Cv8P01IROollZ-on6lAnNi11vXczf0',
    appId: '1:822102067110:ios:af0ed85835d6555f077167',
    messagingSenderId: '822102067110',
    projectId: 'newpjorject',
    storageBucket: 'newpjorject.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu4Sdzdc6ZJxQ25KxD-qrOPPE1FnGqtZU',
    appId: '1:822102067110:web:61966b0ff7aa4e9b077167',
    messagingSenderId: '822102067110',
    projectId: 'newpjorject',
    authDomain: 'newpjorject.firebaseapp.com',
    storageBucket: 'newpjorject.firebasestorage.app',
    measurementId: 'G-RQJSSVB8V3',
  );
}
